baseURL = "https://cnc-101.netlify.app/"
languageCode = "es-es"
title = "CNC 101: Guía para Principiantes"
theme = "PaperMod"

# Configuración para el modo multilingüe (preparado para el futuro)
defaultContentLanguage = "es"

[languages]
[languages.es]
  languageName = "Español"
  weight = 1
  [languages.es.menu]
    [[languages.es.menu.main]]
      identifier = "posts"
      name = "Blog"
      url = "/posts/"
      weight = 5
    [[languages.es.menu.main]]
      identifier = "search"
      name = "Buscar"
      url = "/search/"
      weight = 15

# Parámetros específicos del tema PaperMod
[params]
  env = "production"
  author = "Erick Garcia"
  description = "Tu guía de inicio en el mundo del mecanizado CNC. Aprende desde cero con tutoriales y proyectos."
  defaultTheme = "dark"
  disableThemeToggle = false
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

# --- INICIO: Posts Relacionados y Búsqueda Mejorada ---
# Esta sección activa la búsqueda de posts similares al final de cada artículo
[params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1000
  threshold = 0.4
  minMatchCharLength = 0
  keys = ["title", "permalink", "summary", "content"]

[outputs]
  home = ["HTML", "RSS", "JSON"] # Habilita el index para la búsqueda
